### ISSUE TITLE
Not working on BuddyBoss (which is a fork of BuddyPress)

### ISSUE THREAD

**Issue by ercancoban** [BhargavBhandari90/bp-repost-activity#1]
Hi @BhargavBhandari90 
I installed an activated the plugin.
I am using BuddyBoss. So activated it as an integration there as well.
But when I come to the activity feeds, nothing shows up on the activity feed page.
It says your activity feed is loading please wait.
But at the end nothing changes.

Something is stuck but where?

**Comment by BhargavBhandari90** [comment]
Thanks for reporting this. I am sorry to inform you that currently, it's not working with BuddyBoss. You can expect this with BuddyBoss in my next update.

**Comment by BhargavBhandari90** [comment]
Hi @ercancoban 

I just checked with buddyboss on my local, and it seems it’s working fine. Please have a look into my video.
https://screencast-o-matic.com/watch/cYhoiakXTp

Are you getting any error in console?
